# Customer Lifetime Modeling

In [1]:
import numpy as np

### clv base model infinite time horizon

In [2]:
# variables
p_clv = 5
c_clv = 3
i_clv = .05
r_clv = .65

In [3]:
# AC threshold
ac_max = (p_clv-c_clv)*r_clv/(1+i_clv-r_clv)
print(ac_max)

3.25


### clv with activity probability (ap)

In [7]:
#variables
Tac_ap = -9
Tp_ap = -3
n_ap = 4
i_ap = 0.1
gc_ap = 10

In [5]:
npgc_ap=0
for count in range(1,4):
    npgc_ap = npgc_ap+(((Tp_ap - Tac_ap)/(count-Tac_ap))**n_ap)*gc_ap/((1+i_ap)**count)
print(npgc_ap)

2.379311782094999


### clv with markov

In [9]:
#revenue vector
r = np.array([[-.3],[3.25],[0]])

In [10]:
#transition matrix
p = np.array([[0,.02,.98],[0,.5,.5],[0,0,1]])

In [11]:
#expected value after first period
np.dot(p,r)+r

array([[-0.235],
       [ 4.875],
       [ 0.   ]])

In [14]:
# p^2
np.dot(p,p)

array([[0.  , 0.01, 0.99],
       [0.  , 0.25, 0.75],
       [0.  , 0.  , 1.  ]])

In [15]:
#expected value after second period
np.dot(np.linalg.matrix_power(p,0),r)+np.dot(np.linalg.matrix_power(p,1),r)+np.dot(np.linalg.matrix_power(p,2),r)

array([[-0.2025],
       [ 5.6875],
       [ 0.    ]])

### expected values after infinite periods


In [17]:
# infinite periods with inversion not possible in this case
# THIS WiLl THROW ERROR BECAUSE MATRIX IS NOT INVERTIBLE
np.linalg.inv(np.linalg.matrix_power(p,0)-p)*r


LinAlgError: Singular matrix

In [18]:
# proxy with 100000 iterations since inversion is not possibel
exp_val=np.array([[0],[0],[0]])
for i in range(0,100000):
    exp_val=exp_val+np.dot(np.linalg.matrix_power(p,i),r)
print(exp_val)

[[-0.17]
 [ 6.5 ]
 [ 0.  ]]


In [19]:
# should you stop discounts if return probability without is 30%
r_new = np.array([[-.3],[5],[0]])
p_new = np.array([[0,.02,.98],[0,.3,.7],[0,0,1]])
exp_val_new = np.array([[0],[0],[0]])
for i in range(0,100000):
    exp_val_new=exp_val_new+np.dot(np.linalg.matrix_power(p_new,i),r_new)
print(exp_val_new)

[[-0.15714286]
 [ 7.14285714]
 [ 0.        ]]
